### ISSUE TITLE
Initial alpha development.

### ISSUE THREAD

**Issue by davidicus** [devwatchteam/node-blog#7]
Get node-blog to a place of minimum functionality 

- [x] move express routes to separate files
- [ ] add comment to blog post
- [x] have new tags automatically add to nav cat list
- [ ] add basic styling
- [ ] create static files for complete site
